## **行列積のスクラッチ**

以下のような行列A、Bを考えます。

$$
A=\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix},
B=\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}
$$


NumPyで表すと次のようになります。

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

***

**【問題1】行列積を手計算する**  
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

$$
AB=
\begin{bmatrix}
(-1×0)+(2×0)+(3×2) & (-1×2)+(2×2)+(3×9) & (-1×1)+(2×(-8))+(3×(-1)) \\
(4×0)+(-5×0)+(6×2) & (4×2)+(-5×2)+(6×9) & (4×1)+(-5×(-8))+(6×(-1)) \\
(7×0)+(8×0)+(-9×2) & (7×2)+(8×2)+(-9×9) & (7×1)+(8×(-8))+(-9×(-1))
\end{bmatrix}
=
\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{bmatrix}
$$

***

**【問題2】NumPyの関数による計算**  
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。


[numpy.matmul — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)

[numpy.dot — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

In [2]:
#np.matmul()
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
#np.dot()
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
#@
a_ndarray@ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

《3種類の違い》


np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。


今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。  
>aとbの両方が2次元配列の場合、それは行列の乗算ですが、matmulまたはa @ bの使用が推奨されます。

***

np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

**【問題3】ある要素の計算を実装**  
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1.行列Aの(0,0)の要素 $a_{0,0}$ と行列Bの(0,0)の要素 $b_{0,0}$ を掛け合わせる  
2.行列Aの(0,1)の要素 $a_{0,1}$ と行列Bの(1,0)の要素 $b_{1,0}$ を掛け合わせる  
3.行列Aの(0,2)の要素 $a_{0,2}$ と行列Bの(2,0)の要素 $b_{2,0}$ を掛け合わせる  
4.それら値を全て足し合わせる

数式で表すと
$$
\sum_{k=0}^{2}a_{0,k}b_{k,0} \quad
$$
です。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [5]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

total = 0
for k in range(3):
    total += a_ndarray[0, k]*b_ndarray[k, 0]

#print(total)

***

**【問題4】行列積を行う関数の作成**  
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。

$$
C_{i, j}=\sum_{k=0}^{2}a_{i, k}b_{k, j} \quad
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。

In [6]:
def matrix_product(matrix1, matrix2):
    """
    2つの行列を引数に受け取り、行列積を返す関数
    
    Parameter
    --------
    matrix1：行列1
    matrix2：行列2
    
    Return
    --------
    matrix_product：行列積
    """
    #matrix_productの元となるリスト
    matrix_product_list = []
    
    #各要素を計算してmatrix_product_listに都度追加
    for i in range(matrix1.shape[0]):
        for j in range(matrix2.shape[1]):
            total = 0
            for k in range(matrix1.shape[1]):
                total += matrix1[i, k]*matrix2[k, j]
            matrix_product_list.append(total)
    
    #リストをndarrayにし、適切な形に変形
    matrix_product = np.array(matrix_product_list).reshape(matrix1.shape[0], matrix2.shape[1])
        
    return matrix_product    

In [7]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

matrix_product(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

***

次に以下のような例を考えます。  

$$
D=\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6
\end{bmatrix},
E=\begin{bmatrix}
-9 & 8 & 7 \\
6 & -5 & 4 
\end{bmatrix}
$$

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

In [8]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

matrix_product(d_ndarray, e_ndarray)

IndexError: index 2 is out of bounds for axis 0 with size 2

***

**【問題5】計算が定義されない入力を判定する**  
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [9]:
def matrix_product(matrix1, matrix2):
    """
    2つの行列を引数に受け取り、行列積を返す関数
    
    Parameter
    --------
    matrix1：行列1
    matrix2：行列2
    
    Return
    --------
    matrix_product：行列積
    """
    if matrix1.shape[0] == matrix2.shape[1]:
        #matrix_productの元となるリスト
        matrix_product_list = []

        #各要素を計算してmatrix_product_listに都度追加
        for i in range(matrix1.shape[0]):
            for j in range(matrix2.shape[1]):
                total = 0
                for k in range(matrix1.shape[1]):
                    total += matrix1[i, k]*matrix2[k, j]
                matrix_product_list.append(total)

        #リストをndarrayにし、適切な形に変形
        matrix_product = np.array(matrix_product_list).reshape(matrix1.shape[0], matrix2.shape[1])

        return matrix_product
    
    else:
            print("積を計算できる行列の組み合わせではありません。")

In [10]:
#行列積が計算不可能の場合
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

matrix_product(d_ndarray, e_ndarray)

積を計算できる行列の組み合わせではありません。


In [11]:
#行列積が計算可能の場合
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

matrix_product(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

***

**【問題6】転置**  
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

[numpy.transpose — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

[numpy.ndarray.T — NumPy v1.16 Manual](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html)

In [12]:
#np.transpose()でD行列を転置し、行列積DEの計算
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

d_tr_ndarray = np.transpose(d_ndarray)

matrix_product(d_tr_ndarray, e_ndarray)

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])

In [13]:
#Tアトリビュートを用いてD行列を転置し、行列積DEの計算
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

d_tr_ndarray = d_ndarray.T
matrix_product(d_tr_ndarray, e_ndarray)

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])